server:
  port: 8080
spring:
  application:
    name: moyu_book
  datasource:
    url: jdbc:mysql://47.106.89.121:3306/book?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#  redis:
#    host: localhost
#    port: 6379
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 20MB
#
#QiNiu:
#  url: http://r1puvo5tr.hn-bkt.clouddn.com/
#  accessKey: cmt8RIm7vkOXALWKqTS6dx5rB3dHeqPpF2ARHFMH
#  accessSecretKey: Ny4p6kHioVEf7nNF4Z4We1DDVGF1eirUMA_Q_t27


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix:
#  mapper-locations: classpath*:/com/mszl/blog/dao/mapper/*Mapper.xml



